asciidoc:
  engine: asciidoctor
profiles: 
  production:
    base_url: http://weld.cdi-spec.org
    google_analytics: UA-45187401-1
    deploy: 
      host: github_pages
      branch: master
  github:
    base_url: http://weld.github.io
    deploy: 
      host: github_pages
      branch: master
title: Weld
